config/routes.rb
Rails.application.routes.draw do
  acts_as_archived

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords',
    invitations: 'users/invitations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  match '/impersonate', to: 'users/impersonations#destroy', via: [:delete], as: :impersonate

  if Rails.env.production?
    require 'sidekiq/web'

    authenticate :user, lambda { |user| user.is?(:admin) } do
      mount Sidekiq::Web => '/admin/sidekick'
    end
  end

  match 'test/exception', to: 'test#exception', via: :get
  match 'test/email', to: 'test#email', via: :get

  # Front end
  match '/settings', to: 'users/settings#edit', via: [:get], as: :user_settings
  match '/settings', to: 'users/settings#update', via: [:patch, :put]

  resources :clients, except: [:new, :create]

  resources :mates, only: [:new, :create, :destroy] do
    post :reinvite, on: :member
    post :promote, on: :member
    post :demote, on: :member
  end

  namespace :admin do
    resources :clients, except: [:show], concerns: :acts_as_archived

    resources :mates, only: [:new, :create, :destroy] do
      post :reinvite, on: :member
      post :promote, on: :member
      post :demote, on: :member
    end

    resources :users, except: [:show], concerns: :acts_as_archived do
      post :reinvite, on: :member
      post :impersonate, on: :member
    end

    root to: 'users#index'
  end

  # if you want EffectivePages to render the home / root page
  # uncomment the following line and create an Effective::Page with slug == 'home'
  # root :to => 'Effective::Pages#show', :id => 'home'
  root to: 'static_pages#home'
end

app/views/admin/_navbar.html.haml
%nav.navbar.navbar-default
  .container
    .navbar-header
      = link_to(image_tag('logo-admin.png', alt: 'Admin Logo'), '/', class: 'navbar-brand')
      %button.navbar-toggle.collapsed{data: {toggle: 'collapse', target: '.navbar-collapse', 'aria-expanded': false}}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
    .collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if can? :manage, Effective::Log
          %li= link_to 'Logs', effective_logging.admin_logs_path

        - if can? :manage, Effective::Menu
          %li= link_to 'Menus', effective_pages.admin_menus_path

        - if can? :manage, Effective::Order
          %li= link_to 'Orders', effective_orders.admin_orders_path

        - if can? :manage, Effective::Page
          %li= link_to 'Pages', effective_pages.admin_pages_path

        - if can? :manage, Effective::Post
          %li= link_to 'Posts', effective_posts.admin_posts_path

        - if can? :manage, User
          %li= link_to 'Users', admin_users_path